# Generated by Django 5.1 on 2024-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='health1',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='health1',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
