# Generated by Django 5.1 on 2024-08-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(default='Default Value', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(max_length=300)),
                ('tags', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='agblog/')),
                ('image1', models.ImageField(upload_to='agblog/')),
                ('image2', models.ImageField(upload_to='agblog/')),
            ],
        ),
    ]
